### ISSUE TITLE
Feedback for “DNS over TLS”

### ISSUE THREAD

**Issue by ChrisHills463** [dns-sb/dns.sb#19]
Since you do not support ECS (edns-client-subnet) it would be useful if you provided the addresses of a DNS-over-TLS server in each PoP as you do for DNS-over-HTTPS. Ideally, the sources of these queries should be geolocated to these regions.

**Comment by Showfom** [comment]
Currently our DoT servers are located in the following cities:

Frankfurt, Germany
Duesseldorf, Germany
Amsterdam, the Netherlands
Tallinn, Estonia
London, UK
San Jose, CA, United States
Osaka, Japan
Tokyo, Japan
Hong Kong, China
Sydney, Australia

We advise against using our DoT service outside of these regions due to high latency issues and inaccurate geo-location data.
